[package]
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
categories = ["gui", "os::linux-apis", "api-bindings"]
description = "XDG portals wrapper in Rust using zbus"
edition = "2018"
exclude = ["interfaces/*.xml"]
keywords = ["portal", "flatpak", "xdg", "desktop", "documents"]
license = "MIT"
name = "ashpd"
repository = "https://github.com/bilelmoussaoui/ashpd"
version = "0.1.0"

[features]
feature_gtk = ["gdk", "gdkx11", "gtk"]

[dependencies]
enumflags2 = "0.6"
gdk = {version = "0.13", optional = true}
gtk = { version = "0.9", optional = true}
gdkx11 = {version = "0.9", optional = true}
serde = {version = "1.0", features = ["derive"]}
serde_repr = "0.1"
strum = "0.20"
strum_macros = "0.20"
zbus = {version = "1.3"}
zvariant = {version = "2.3", features = ["enumflags2"]}
zvariant_derive = {version = "2.3"}
