[package]
name = "libportal"
version = "0.1.0"
description = "xdg-desktop-portal implementation"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"
repository = "https://github.com/bilelmoussaoui/libportal-rs"
exclude = ["interfaces/*.xml"]
keywords = ["portal", "flatpak", "xdg", "desktop", "documents", "desktop"]
license = "MIT"

[dependencies]
zbus = "1.1"
zvariant = "2.1"
zvariant_derive = "2.1"
serde = "1.0"
