[package]
name = "libportal"
version = "0.1.0"
description = "xdg-desktop-portal implementation"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"
repository = "https://github.com/bilelmoussaoui/libportal-rs"
exclude = ["interfaces/*.xml"]
keywords = ["portal", "flatpak", "xdg", "desktop", "documents"]
license = "MIT"

[dependencies]
zbus = { git="https://gitlab.freedesktop.org/zeenix/zbus" }
zvariant = { git="https://gitlab.freedesktop.org/zeenix/zbus" }
zvariant_derive = { git="https://gitlab.freedesktop.org/zeenix/zbus" }
serde = "1.0"
serde_repr = "0.1"
