[package]
name = "ashpd"
version = "0.1.0"
description = "XDG portals wrapper in Rust using zbus"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"
repository = "https://github.com/bilelmoussaoui/ashpd"
exclude = ["interfaces/*.xml"]
keywords = ["portal", "flatpak", "xdg", "desktop", "documents"]
license = "MIT"

[features]
gdk_color = ["gdk"]


[dependencies]
zbus = { version = "1.1" }
zvariant = { version = "2.2", features = ["enumflags2"] }
zvariant_derive = { version = "2.2" }
serde = {version = "1.0", features = ["derive"] }
serde_repr = "0.1"
strum = "0.19"
strum_macros = "0.19"
enumflags2 = "0.6"
gdk = {version = "0.13", optional = true}

