[package]
name = "ashpd-demo"
version = "0.2.3"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk-macros = "0.3"
once_cell = "1.9"
futures = "0.3"
gst = {package="gstreamer", version = "0.18"}
gst4gtk = { package = "gst-plugin-gtk4", version = "0.1"}
gtk = {package = "gtk4", version = "0.4"}
adw = {version = "0.1", package = "libadwaita"}
serde = {version = "1.0", features = ["derive"]}
chrono = {version = "0.4", default-features = false}

[dependencies.shumate]
package = "libshumate"
version = "0.1.0-alpha.4"

[dependencies.ashpd]
version = "0.2.2"
features = ["feature_gtk4", "feature_pipewire", "log"]
