[package]
name = "ashpd-demo"
version = "0.1.0"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk-macros = "0.3"
once_cell = "1.9"
futures = "0.3"
gst = {package="gstreamer", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"}
gst4gtk = { package = "gst-plugin-gtk4", git = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/"}
gtk = {package = "gtk4", git = "https://github.com/gtk-rs/gtk4-rs"}
adw = {git = "https://gitlab.gnome.org/World/Rust/libadwaita-rs", package = "libadwaita"}
serde = {version = "1.0", features = ["derive"]}
chrono = {version = "0.4", default-features = false}

[dependencies.shumate]
package = "libshumate"
git = "https://gitlab.gnome.org/World/Rust/libshumate-rs"

[dependencies.ashpd]
git = "https://github.com/bilelmoussaoui/ashpd"
features = ["feature_gtk4", "feature_pipewire", "log"]
