on:
  push:
    branches: [master]
  pull_request:
name: Demo CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64] # add aarch64 once we move to gnome-42 image
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    # Docker is required by the docker/setup-qemu-action which enables emulation
    - name: Install deps
      run: |
        dnf -y install docker
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        repository-name: "flathub-beta"
        bundle: "ashpd-demo.flatpak"
        manifest-path: "ashpd-demo/build-aux/com.belmoussaoui.ashpd.demo.Devel.json"
        run-tests: "true"
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}
