name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    container:
      image: docker.io/bilelmoussaoui/gtk4
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo dnf install -y gtk3-devel
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Z unstable-options --extern-html-root-url=zbus=https://docs.rs/zbus/ --extern-html-root-url=zvariant=https://docs.rs/zvariant/ --extern-html-root-url=enumflags2=https://docs.rs/enumflags2/0.6/
        with:
          command: doc
          args: --package ashpd --all-features --no-deps

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/doc/
